<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>Rubezh.Stage4.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../game/core/**/*.cs" />
  </ItemGroup>
</Project>
